### ISSUE TITLE
Update references to Terra's classes in docstrings

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-community/qiskit-machine-learning#474]
### What is the expected enhancement?

Review all docstrings in the package and update references to Terra's classes. For instance, in the `VQC` documentation we reference \`\`ZZFeatureMap\`\` that is in `qiskit.circuit.library`. When the package documentation is generated, the reference becomes just a plain text. Such references should be replaced with cross references, that are replaced in the generated documentations with corresponding links. In this example, in the documentation \`\`ZZFeatureMap\`\` to be replaced with \`:class:\`~qiskit.circuit.library.ZZFeatureMap\`. Then in the html documentation this cross reference will become a link to the corresponding class in Terra.

**Comment by adekusar-drl** [comment]
Yes, this is correct.

**Comment by adekusar-drl** [comment]
Ok, I assigned this issue to you as well. But if you don't have time to work on any of them, let me know.

**Comment by SamD-1998** [comment]
Is there something else that is yet to be completed in this issue?

**Comment by adekusar-drl** [comment]
Considering the lack of progress and the time passed since the last message, I think, it is an issue that anybody can give a try.

**Comment by woodsp-ibm** [comment]
Closed as done by #700
