### ISSUE TITLE
Add unit tests that run on either backend-based primitives or Aer primitives

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-community/qiskit-machine-learning#504]
### What is the expected enhancement?

New QML classes that leverage Qiskit primitives are tested only on the reference implementation available in Terra, e.g. `Sampler` and `Estimator`. This issue is created to discuss and implement new unit tests for the classes that are built on top of primitives, e.g. `SamplerQNN`, `EstimatorQNN`, quantum kernel classes.

**Comment by woodsp-ibm** [comment]
Maybe for this perhaps its more Neko type tests. The reference primitives should be fine for unit testing, its just to check the ML functional correctness - they can have ideal and shot/variance behavior. To do different primitives would be more towards system tests than unit tests in my mind.

**Comment by adekusar-drl** [comment]
Closing as irrelevant.
