### ISSUE TITLE
QKT deepcopies kernel internally, fails with runtime primitives

### ISSUE THREAD

**Issue by ElePT** [qiskit-community/qiskit-machine-learning#600]
### Environment

- **Qiskit Machine Learning version**: 0.6.0
- **Python version**: all
- **Operating system**: all

### What is happening?

On line 202, the quantum kernel trainer performs: `output_kernel = copy.deepcopy(self._quantum_kernel)`, which is incompatible with the runtime primitives, as they do not support `deepcopy`. If you try to run it, a recursion error is raised (this does not happen with the Terra reference or Aer primitives).

### How can we reproduce the issue?

See the original issue: https://github.com/Qiskit/qiskit-ibm-runtime/issues/745

### What should happen?

The QKT class should work seamlessly for all primitives.

### Any suggestions?

I think it's worth revising whether we need to copy the kernel, or whether we need to return a kernel at all. 

- One possibility would be for the QKT class to return the trained paremeters and have the user deal with them as they wish (downside -> breaks current interface) 
- Another possibility would be to develop a more sophisticated `kernel.copy` that creates a new kernel without copying the primitive
- Finally, we could have the QKT modify the original kernel object

**Comment by adekusar-drl** [comment]
I'm looking into the issue. Sorry for the delay

**Comment by ElePT** [comment]
@adekusar-drl There is a chance this PR has fixed the behavior: https://github.com/Qiskit/qiskit-ibm-provider/pull/658, I am not sure if the runtime primitives use the `IBMBackend` class internally.

**Comment by oscar-wallis** [comment]
Hiya, this issue should be fixed within the springv1 Hartree centre qml PR.
