### ISSUE TITLE
Update the Quantum Neural Networks tutorial with QNNCircuit

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-community/qiskit-machine-learning#613]
### What should we add?

With the recent introduction of `QNNCircuit` it is important to show how to use it in the QML tutorials. The most suitable opportunity is to update the `01_neural_networks.ipynb` and add a simplified way of instantiating quantum neural networks. Other tutorials can be updated as well.

**Comment by david-alber** [comment]
@adekusar-drl great idea 👍 !
I'd love to pick up this one 😃 .

**Comment by athanzxyt** [comment]
Hey @adekusar-drl ! Would it be possible for me also to be assigned to this issue? I'd love to help improve the QML tutorials.

**Comment by adekusar-drl** [comment]
@david-alber are there any updates?

**Comment by david-alber** [comment]
@adekusar-drl  I am still working on this issue. We can split the work though: I will update the ``01_neuronal_networks.ipynb`` tutorial. @athanzxyt  if you find any other tutorials where the ``QNNCircuit`` can be applied, please go ahead and do the updates 😀.

**Comment by adekusar-drl** [comment]
@athanzxyt You can think where `QNNCircuit` can be applied else. Thanks.

**Comment by Jay-Patel-257** [comment]
@adekusar-drl Can you reference the API documentation for `QNNCircuit`? I could not find anything related to `QNNCircuit`.

**Comment by adekusar-drl** [comment]
The documentation is not available since it is not released yet.

**Comment by Jay-Patel-257** [comment]
Ahh, alright!
