### ISSUE TITLE
SamplerQNN GPU

### ISSUE THREAD

**Issue by contepablod** [qiskit-community/qiskit-machine-learning#650]
### What should we add?

Does the class SamplerQNN accepts GPU? I am passing inside the sampler=sampler where sampler is 
``sampler=Sampler()
sampler.set_options(backend=simulator_gpu, device='GPU')
sampler.options``
Options(backend=AerSimulator('aer_simulator_gpu'), device='GPU')

The QNNclass is not triggering the GPU, goes by CPU

Any insights?

Already uninstall qikist-aer and install qiski-aer-gpu

**Comment by adekusar-drl** [comment]
As I mentioned on Slack `SamplerQNN` does nothing with Sampler except it executes circuits through it. So, if a sampler instance makes use of GPU, then the QNN would make use of GPU as well.

**Comment by adekusar-drl** [comment]
I'm closing the issue as completed. Feel free to re-open if required.

**Comment by contepablod** [comment]
Thanks Anton! I've managed to use it!
