### ISSUE TITLE
The results from SamplerQNN.forward() and the circuit using bind_parameters() are very different

### ISSUE THREAD

**Issue by kjh101402** [qiskit-community/qiskit-machine-learning#671]
### Environment

- **Qiskit Machine Learning version**: 0.6.1
- **Python version**: 3.8.16
- **Operating system**: windows 11, ubuntu 20.04.6

### What is happening?

Firstly, my English isn't great, so my writing may be strange.

I'm using SamplerQNN.

When using SamplerQNN's forward, I noticed that input_data and weights are not applied to input_params and weight_params. 

That's why the results of SamplerQNN's forward are different from the measurement results of the circuit created directly with bind_parameters().

### How can we reproduce the issue?

```python
# 1. make feature_map
n = 2
feature_map = QuantumCircuit(n, name='Embed')
x0 = Parameter('x0')
x1 = Parameter('x1')
feature_map.rx(x0, 0)
feature_map.rx(x1, 1)

for i in range(n):
    feature_map.ry(pi/4, i)
for i in range(n):
    feature_map.rz(pi/4, i)

# 2. make ansatz
param = []
for i in range(4):
    param.append((Parameter('a'+str(i))))

ansatz = QuantumCircuit(n, name = 'PQC')

for i in range(n):
    ansatz.ry(param[i], i)
for i in range(n):
    ansatz.rz(param[i+n], i)


# 3. make interpret
parity = lambda x: format(x, 'b').zfill(2).count('1') % 2


# 4. compose circuit
qc = QuantumCircuit(n)
qc.compose(feature_map, inplace=True)
qc.compose(ansatz, inplace=True)

qc.draw()


# 5. make SamplerQNN
qnn = SamplerQNN(
    circuit = qc, 
    input_params = feature_map.parameters,
    weight_params = ansatz.parameters,
    interpret = parity,
    output_shape = 2
)

# 6.  SamplerQNN forward

qnn.forward(input_data = [1, 2], weights = [1, 2, 3, 4])

#result : array([[0.47770986, 0.52229014]])
```

```python
# 7. make bind_parameters circuit
com_qc = qc.copy()
com_qc.measure_all()
com_qc.draw()
bc = com_qc.bind_parameters({x0:1, x1:2, param[0]:1, param[1]:2, param[2]:3, param[3]:4})
bc.draw()


# 8. measure circuit
shot = 1024

backend = Aer.get_backend('qasm_simulator')
job = backend.run(bc.decompose(), shots = shot)
result = job.result()

counts = result.get_counts()
print(counts)
zero = 0
one = 0
for measure, count in counts.items():
    if measure.count('1') % 2 == 0:
        zero += count
    else:
        one += count

prob = [zero / shot, one / shot]
print(prob)

# result: [0.560546875, 0.439453125]

```

### What should happen?

The measurement results will continue to change, but they will definitely be different from the results of SamplerQNN.forward().

SamplerQNN's result is array([[0.47770986, 0.52229014]]), but when I convert the measurements from the circuit using bind_parameters to probabilities, I get [0.560546875, 0.439453125].

### Any suggestions?

I wondered why, so I looked at SamplerQNN's source code. If you look at the parameter_values in the return value of _preprocess_forward(input_data, weights) in the _forward function of SamplerQNN, it concatenates in the order [input_data, weights]. 

location : 
qiskit_machine_learning/neural_networks/sampler_qnn.py (line 347)
qiskit_machine_learning/neural_networks/neural_network.py (line 147)

```python
def _forward(
        self,
        input_data: np.ndarray | None,
        weights: np.ndarray | None,
    ) -> np.ndarray | SparseArray | None:
        """
        Forward pass of the network.
        """
        parameter_values, num_samples = self._preprocess_forward(input_data, weights)

        # sampler allows batching
        job = self.sampler.run([self._circuit] * num_samples, parameter_values)
        try:
            results = job.result()
        except Exception as exc:
            raise QiskitMachineLearningError("Sampler job failed.") from exc
        result = self._postprocess(num_samples, results)

        return result
```
```python
def _preprocess_forward(
        self,
        input_data: np.ndarray | None,
        weights: np.ndarray | None,
    ) -> tuple[np.ndarray | None, int | None]:
        """
        Pre-processing during forward pass of the network for the primitive-based networks.
        """
        if input_data is not None:
            num_samples = input_data.shape[0]
            if weights is not None:
                weights = np.broadcast_to(weights, (num_samples, len(weights)))
                parameters = np.concatenate((input_data, weights), axis=1)
            else:
                parameters = input_data
        else:
            if weights is not None:
                num_samples = 1
                parameters = np.broadcast_to(weights, (num_samples, len(weights)))
            else:
                # no input, no weights, just execute circuit once
                num_samples = 1
                parameters = np.asarray([])
        return parameters, num_samples
```

Then we looked at the code in the sampler. I looked at the part in _call where it uses bind_parameters and printed it out. When I printed it out, I saw that bind didn't get to the parameters I wanted. This seems to be caused by the order of self._parameters and values being out of order, so fixing the concatenate in _preprocess_forward() should fix the problem.

location: qiskit/primitives/sampler.py (line 67)
```python
def _call(
...

        for i, value in zip(circuits, parameter_values):
            if len(value) != len(self._parameters[i]):
                raise QiskitError(
                    f"The number of values ({len(value)}) does not match "
                    f"the number of parameters ({len(self._parameters[i])})."
                )
            bound_circuits.append(
                self._circuits[i]
                if len(value) == 0
                else self._circuits[i].bind_parameters(dict(zip(self._parameters[i], value)))
            )
            print(dict(zip(self._parameters[i], value)))


```
output:
{Parameter(a0): 1.0, Parameter(a1): 2.0, Parameter(a2): 1.0, Parameter(a3): 2.0, Parameter(x0): 3.0, Parameter(x1): 4.0}

**Comment by adekusar-drl** [comment]
Thanks for reporting this. It is a tricky issue and unlikely it will be fixed. This issue should have been properly documented. Parameters in a quantum circuit are stored in the alphabetical order, e.g. if you add a data parameter `x0` and a weight `a0`, then in the circuit they are stored as `["a0", "x0"]`. You can check it out by printing `qc.parameters`, you'll see the sequence of the parameters. Then, when `SamplerQNN.forward()` is called, it concatenates input data with weights into a single array of all parameters. At this moment a sequence of parameters in the circuit plays a crucial role. The QNN assumes that first were added data parameters and then weights. If the sequence is incorrect, then the values are bound to incorrect parameters. This is what is happened here in the snippet. If you name your input parameters as `a` and weights as `b`, you should get the correct output. Keep in mind that you have QASM simulator, it brings in additional noise.

**Comment by adekusar-drl** [comment]
And since the order of the way of parameters were added to a circuit is unpredictable (it's up to the user), it is impossible to fix concatenation in `_preprocess_forward()`. Hope it is clear.

**Comment by kjh101402** [comment]
Thank you for your response. That was very helpful.
