### ISSUE TITLE
Add Quantum Bayesian Inference

### ISSUE THREAD

**Issue by proeseler** [qiskit-community/qiskit-machine-learning#699]
### What should we add?

 Is there any ongoing work on Quantum Bayesian Inference?

Otherwise, I am currently working on a framework for quantum Bayesian inference and would like to include it soon.

The framework is based on:
[https://www.sciencedirect.com](https://www.sciencedirect.com/science/article/abs/pii/S0957417421002098)
[https://journals.aps.org](https://journals.aps.org/pra/pdf/10.1103/PhysRevA.89.062315?casa_token=acbtd9TnExsAAAAA%3AJ-cok2SSN36En5pGocqfen9xB7aRc_93QGWzgNf9OrlVIr5OtQmbiZq-cSXJU4HSa5mk3NS9NyCe1Q)

**Comment by edoaltamura** [comment]
This implementation was merged in https://github.com/qiskit-community/qiskit-machine-learning/pull/717, and the issue can be closed.

**Comment by edoaltamura** [comment]
Closing this issue.
