### ISSUE TITLE
Update tutorials for deprecated circuit draw style

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-machine-learning#725]
A number of Tutorials have this deprecation warning message. The drawing should be updated to avoid this.

`qc.draw("mpl")`

>/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/visualization/circuit/matplotlib.py:266: FutureWarning: The default matplotlib drawer scheme will be changed to "iqp" in a following release. To silence this warning, specify the current default explicitly as style="clifford", or the new default as style="iqp".
  self._style, def_font_ratio = load_style(self._style)

These are the tutorials - I just put the number not the full name. There can be multiple places within each that needs fixing.

- [x] 01
- [x] 02
- [x] 02a
- [x] 04
- [x] 05
- [x] 10
- [x] 11 (updated by #728)
- [x] 12

**Comment by edoaltamura** [comment]
Fixed by 30aa648b1eb82527a9bfb6be9173c5f526f18b4e for all tutorials: `qc.draw("mpl")` -> `qc.draw("mpl", style="clifford")`. This closes also https://github.com/OkuyanBoga/hc-qiskit-machine-learning/issues/11 and the update is available there after syncing the fork.
