### ISSUE TITLE
GAN for RGB imagesin qskit

### ISSUE THREAD

**Issue by Elyon7** [qiskit-community/qiskit-machine-learning#730]
i would like to get this code working in order to generate RGB images (64x64x3) with GAN in qskit.
I started from this code: https://qiskit.org/ecosystem/machine-learning/tutorials/04_torch_qgan.html
But this is not for images. I have problems with the generator because in the tutorial does not receive any noise as input, while I think it is necessary in GAN for images. How can I change the generator?
Is the quantum qskit circuit suitable for my purpose?

**Comment by oscar-wallis** [comment]
Hi @Elyon7, could you help me out by providing a bit more context to the scope of your problem by answering the questions below, the more detail, the better I can help you back!

1. What RGB images are you trying to generate?
2. What are they trying to mimic?
3. How do you plan on verifying the images are correct? What kind of network?
4. Where do you want to add noise and why?
