### ISSUE TITLE
Support V2 primitives

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-machine-learning#742]
### What should we add?

The Sampler and Estimator are being updated with new V2 versions that change the interface and will be available from Qiskit 1.0.0. V1 versions will at some point be deprecated and removed. Algorithms should add support for V2 versions and ultimately drop support for V1 once they are removed.

Related to qiskit-community/qiskit-algorithms/issues/136

**Comment by declanmillar** [comment]
Just to add, the deadline for this is August 15, 2024. See [here]( https://docs.quantum.ibm.com/announcements/product-updates/2024-07-15-v1-support-ending).

**Comment by aritra90** [comment]
Hi, any update on when the support V2 primitives will be added and ready to be used? 
Thanks for all the hard work 👍

**Comment by edoaltamura** [comment]
To follow up,@aritra90, the upcoming version 0.8 will include support for V2 primitives and we expect to release it at the end of October 2024.
