### ISSUE TITLE
ISA circuit support for latest Runtime

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-machine-learning#786]
https://docs.quantum.ibm.com/announcements/product-updates/2024-02-14-qiskit-runtime-primitives-update

> **beginning 1 March 2024**, Qiskit Runtime will require that circuits and observables are transformed to use only instructions supported by the system (referred to as instruction set architecture (ISA) circuits and observables) before being submitted to the primitives

This affects the existing V1 primitves, as supported here, as well as the newly introduced V2 ones which are yet to be supported, see #742

In cases in maybe that the user can already pass a transpiled circuit, in some cases where its two circuits that joined, feature map and ansatz, care would be needed. Observables need to match the layout too. Anyway the situation needs investigation to determine how to proceed.

ML also makes use of Qiskit Algorithms for which there is an open issue too on the same subject https://github.com/qiskit-community/qiskit-algorithms/issues/164 and though I have linked this for reference I think the dependence is more around optimizers and other logic that is independent of the primitives, except for use of the gradients which most likely needs further investigation around whether ISA circuits can be directly used with these, or do they need any alteration.

**Comment by woodsp-ibm** [comment]
Just noting this as it came up. Using tutorial 2 now with a runtime Sampler and QNNCircuit where it needs to be an ISA circuit. When you transpile that to pass it as an ISA circuit one needs to be explicit about input and weights as this logic https://github.com/qiskit-community/qiskit-machine-learning/blob/main/qiskit_machine_learning/neural_networks/sampler_qnn.py#L187-L192 will no longer see it as a QNNCircuit instance. Also without clbits we should probably think about doing a measure_active() rather than a measure_all().

**Comment by oscar-wallis** [comment]
@woodsp-ibm, is the issue here just we need to updates our ML algs to use V2 primitives, being careful with passing inputs and weights? A fairly large overhaul but not much of a challenge, the new documentation makes it seem easy enough.

**Comment by woodsp-ibm** [comment]
@oscar-wallis No, supporting V2 primitives is a separate thing. For them, and for the current V1 primitives since March, IBM Runtime requires the circuit to be an ISA circuit as input to its primitives and no longer supports logical circuits - ie they must be already transpiled to the target device to be valid. The new V2 primitives need this as well so it needs to be done either way. Note the the V1 primitives in Runtime are already deprecated as of the 0.23 release mid April and they will be removed completely in the not too distant future.

**Comment by declanmillar** [comment]
Just to add, the deadline for this is August 15, 2024. See [here]( https://docs.quantum.ibm.com/announcements/product-updates/2024-07-15-v1-support-ending).
