### ISSUE TITLE
Revamp `README.md` with structured information

### ISSUE THREAD

**Issue by edoaltamura** [qiskit-community/qiskit-machine-learning#790]
### What should we add?

Restructure the Readme file with a more structured introduction. Proposal:

> ## What is <>?
> 
> ## How do I install <>?
> 
> You can install <> from the Python Package Index (PyPI) by running:
> 
> ```
> pip install <>
> ```
> 
> It is also possible to install <> using `conda`:
> 
> ```
> conda install -c conda-forge <>
> ```
> 
> Our [Get Started guide](https://<>/install.html) contains full installation instructions and includes how to set up Python virtual environments.
> 
> ### Installation from source
> To access the latest version before its official release, install it from the `main` branch.
> ```
> pip install git+https://github.com/<>@main
> ```
> 
> ## What are the main features of <>?
> 
> ## How do I use <>?
> 
> ## Why does <> exist?
> 
> ## The maintainers
> 
> - STFC Hartree
> - IBM Quantum
> - Open source contributors
> 
> ## Can I contribute?
> 
> We welcome all kinds of contributions. Check out our [guide to contributing]().
> 
> ## Where can I learn more?
> 
> There is a growing community. We encourage you to ask and answer technical questions on [Slack]().
> 
> ## How can I cite <>?
> 
> If you're an academic, <> can also help you, for example, as a tool to do [...]. Use the "Cite this repository" button on [our repository]() to generate a citation from the [CITATION.cff file]().
> 
> ## Python version support policy
> * The core [<> Framework]() supports all Python versions that are actively maintained by the CPython core team. When a [Python version reaches end of life](https://devguide.python.org/versions/#versions), support for that version is dropped. This is not considered a breaking change.

**Comment by woodsp-ibm** [comment]
As a general comment you can see the existing sections followed the same pattern as Qiskit (same for the other applications and algorithms). In the past it was helpful since if needed/wanted any changes were similar across the set of repos. With the repos now under more individual maintainership having something different seems fine. As to sections like where to learn more and how to use - I would have thought tutorials and how to docs. Qiskit Nature started to add them in trying to do the docs more in the diataxis form, so the how to section would point to howtos when they existed. As to the Python support policy what versions have more come down to Qsikit since thats a key dependent. Once a version hits its support EOL then it does get dropped, it may take a while though for a new version to get supported based on how quickly all the key dependents support that new version.

**Comment by edoaltamura** [comment]
We could also add the following shields:

[![License](https://img.shields.io/github/license/qiskit-community/qiskit-machine-learning.svg?)](https://opensource.org/licenses/Apache-2.0) 
[![Current Release](https://img.shields.io/github/release/qiskit-community/qiskit-machine-learning.svg?logo=Qiskit)](https://github.com/qiskit-community/qiskit-machine-learning/releases)
[![Extended Support Release](https://img.shields.io/github/v/release/qiskit-community/qiskit-machine-learning?sort=semver&filter=0.*&logo=Qiskit&label=extended%20support)](https://github.com/qiskit-community/qiskit-machine-learning/releases?q=tag%3A0)
[![Build Status](https://github.com/qiskit-community/qiskit-machine-learning/actions/workflows/main.yml/badge.svg)](https://github.com/qiskit-community/qiskit-machine-learning/actions?query=workflow%3A"Machine%20Learning%20Unit%20Tests"+branch%3Amain+event%3Apush)
[![Monthly downloads](https://img.shields.io/pypi/dm/qiskit-machine-learning.svg)](https://pypi.org/project/qiskit-machine-learning/)
[![Coverage Status](https://coveralls.io/repos/github/qiskit-community/qiskit-machine-learning/badge.svg?branch=main)](https://coveralls.io/github/qiskit-community/qiskit-machine-learning?branch=main)
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/qiskit-machine-learning)
[![Total downloads](https://static.pepy.tech/badge/qiskit-machine-learning)](https://pepy.tech/project/qiskit-machine-learning)
[![Slack Organisation](https://img.shields.io/badge/slack-chat-blueviolet.svg?label=Qiskit%20Slack&logo=slack)](https://slack.qiskit.org)

And finally the badge for https://www.bestpractices.dev/en/criteria/0

**Comment by edoaltamura** [comment]
Issue https://github.com/qiskit-community/qiskit-machine-learning/issues/807 can be thought of as part of this README update.

**Comment by edoaltamura** [comment]
Now that some of the `README.md` is updated, the outstanding points to improve are:
* Restructured outlook of the main features
* Restructured quickstart example
* Instructions to install from source
* A list of _Awesome Qiskit Machine Learning_ [![Awesome](https://awesome.re/badge.svg)](https://awesome.re) projects anywhere else on GitHub which demonstrate neat functionalities perhaps implemented in research papers.
