### ISSUE TITLE
Error when testing samples with labels other than {0, 1} in the MNIST dataset.

### ISSUE THREAD

**Issue by phanducthien82** [qiskit-community/qiskit-machine-learning#794]
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

I followed the instructions in the document "Torch Connector and Hybrid QNNs." When running with samples labeled 0 and 1, it works fine. However, when I change the data to distinguish samples with other labels (e.g., 6 and 8 or any other pair), the training throws an error: "IndexError: Target 8 is out of bounds." Has anyone encountered this problem? Please suggest a solution. Thank you!
<img width="567" alt="err1" src="https://github.com/qiskit-community/qiskit-machine-learning/assets/76273668/15f3b1f6-160c-411a-91cf-2e148d6c3157">

### How can we reproduce the issue?

# Train Dataset
# -------------

# Set train shuffle seed (for reproducibility)
manual_seed(42)

batch_size = 1
n_samples = 100 # we will concentrate on the first 100 samples

# Use pre-defined torchvision function to load MNIST train data
X_train = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

# Filter out labels (originally 0-9), leaving only label 0 and 1
idx = np.append(
    np.where(X_train.targets == 6)[0][:n_samples],
    np.where(X_train.targets == 8)[0][:n_samples]
)
X_train.data = X_train.data[idx]
X_train.targets = X_train.targets[idx]

# Define torch dataloader with filtered data
train_loader = DataLoader(X_train, batch_size=batch_size, shuffle=True)

### What should happen?

<img width="567" alt="err1" src="https://github.com/qiskit-community/qiskit-machine-learning/assets/76273668/2fe808f4-5a07-4598-85b9-b01426dec9f8">

**Comment by edoaltamura** [comment]
Hi, @phanducthien82, thanks for raising this. Just to check, what version of Qiskit machine learning are you using?

The code snippets you shared are useful, however, it would be even more helpful to have complete code from start to end that shows the buggy behaviour. This would help us look for potential issues and advise on library usage. Would you be able to share the code in this thread?

**Comment by phanducthien82** [comment]
[06_torch_connector](https://www.kaggle.com/code/phanducthien/06-torch-connector)
This is my cocde

**Comment by edoaltamura** [comment]
@phanducthien82 you may need to save it explicitly in Kaggle, or at least I couldn't find your code at the link. Apart from that, I'd recommend posting the code in a comment here _directly_, instead of Kaggle, for consistency. Hope this helps!

**Comment by phanducthien82** [comment]
This is my code
`import numpy as np
import matplotlib.pyplot as plt

from torch import Tensor
from torch.nn import Linear, CrossEntropyLoss, MSELoss
from torch.optim import LBFGS

from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes, ZZFeatureMap
from qiskit_algorithms.utils import algorithm_globals
from qiskit_machine_learning.neural_networks import EstimatorQNN, SamplerQNN
from qiskit_machine_learning.connectors import TorchConnector

# set seed for random generators
algorithm_globals.random_seed = 42

# Additional torch-related imports
import torch
from torch import cat, no_grad, manual_seed
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.optim as optim
from torch.nn import (
    Module,
    Conv2d,
    Linear,
    Dropout2d,
    NLLLoss,
    MaxPool2d,
    Flatten,
    Sequential,
    ReLU,
)
import torch.nn.functional as F

# Train Dataset
# -------------

# Set train shuffle seed (for reproducibility)
manual_seed(42)

batch_size = 1
n_samples = 100 # we will concentrate on the first 100 samples

# Use pre-defined torchvision function to load MNIST train data
X_train = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

# Filter out labels (originally 0-9), leaving only label 0 and 1
idx = np.append(
    np.where(X_train.targets == 6)[0][:n_samples],
    np.where(X_train.targets == 8)[0][:n_samples]
)
X_train.data = X_train.data[idx]
X_train.targets = X_train.targets[idx]

# Define torch dataloader with filtered data
train_loader = DataLoader(X_train, batch_size=batch_size, shuffle=True)

n_samples_show = 6
data_iter = iter(train_loader)

fig, axes = plt.subplots(nrows=1, ncols=n_samples_show, figsize=(10, 3))

while n_samples_show > 0:
    images, targets = data_iter.__next__()
    
    axes[n_samples_show - 1].imshow(images[0, 0].numpy().squeeze(), cmap="gray")
    axes[n_samples_show - 1].set_xticks([])
    axes[n_samples_show - 1].set_yticks([])
    axes[n_samples_show - 1].set_title("Labeled: {}".format(targets[0].item()))
    
    n_samples_show -= 1

# Test Dataset
# ------------

# Set test shuffle seed (for reproducibility)
# manual_seed(42)

n_samples = 50

# Use pre-defined torchvision function to load MNIST test data
X_test = datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

# Filter out labels (origined 0-9), leaving only labels 0 and 1
idx = np.append(
    np.where(X_test.targets==6)[0][:n_samples],
    np.where(X_test.targets==8)[0][:n_samples]
)
X_test.data = X_test.data[idx]
X_test.targets = X_test.targets[idx]

# Define torch dataloader with filtered data
test_loader = DataLoader(X_test, batch_size=batch_size, shuffle=True)

# Define and create QNN
def create_qnn():
    feature_map = ZZFeatureMap(2)
    ansatz = RealAmplitudes(2, reps=1)
    qc = QuantumCircuit(2)
    qc.compose(feature_map, inplace=True)
    qc.compose(ansatz, inplace=True)
    
    # REMEMBER TO SET input_gradients=True FOR ENABLING HYBRID GRADIENT BACKPROP
    qnn = EstimatorQNN(
        circuit = qc,
        input_params = feature_map.parameters,
        weight_params = ansatz.parameters,
        input_gradients = True, # allow hybrid gradient backprob
    )
    return qnn

qnn4 = create_qnn()

# Define torch NN module
class Net(Module):
    def __init__(self, qnn):
        super(Net, self).__init__()
        self.conv1 = Conv2d(1, 2, kernel_size=5)
        self.conv2 = Conv2d(2, 16, kernel_size=5)
        self.dropout = Dropout2d()
        self.fc1 = Linear(256, 64)
        self.fc2 = Linear(64, 2) # 2-dimensional input to QNN
        self.qnn = TorchConnector(qnn) # Apply torch connector, weight chosen uniformly at random from interval [-1, 1]
        self.fc3 = Linear(1, 1) # 1-dimensional output from QNN
        
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)
        x = self.dropout(x)
        x = x.view(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.qnn(x) # Apply QNN
        x = self.fc3(x)
        return cat((x, 1 - x), -1)
    
model4 = Net(qnn4)

# Define model, optimizer, and loss function
optimizer = optim.Adam(model4.parameters(), lr=0.001)
loss_func = NLLLoss()

# Start training
epochs = 10  # Set number of epochs
loss_list = []  # Store loss history
model4.train()  # Set model to training mode

for epoch in range(epochs):
    total_loss = []
    for batch_idx, (data, target) in enumerate(train_loader):
        optimizer.zero_grad(set_to_none=True)  # Initialize gradient
        output = model4(data)  # Forward pass
        loss = loss_func(output, target)  # Calculate loss
        loss.backward()  # Backward pass
        optimizer.step()  # Optimize weights
        total_loss.append(loss.item())  # Store loss
    loss_list.append(sum(total_loss) / len(total_loss))
    print("Training [{:.0f}%]\tLoss: {:.4f}".format(100.0 * (epoch + 1) / epochs, loss_list[-1]))
`

**Comment by oscar-wallis** [comment]
## Explanation
Hi @phanducthien82, so I used the code you posted above - there isn't a bug just a slight mistake in your code. All that's happening is that you're inputting a target of 6 and 8 directly into the loss function, which is expecting either a 0 or 1, as there are 2 classes. There is a little more to it once you start getting into output shapes and numbers of classes and internal one hot encoding but an easy fix is just to make sure your target array has values 0 where the image is the number 6 and values 1 where the image is the number 8. If you want to extend this to say 3 classes of images, say images of the numbers 6, 7, and 8, then you would need to have targets of 0, 1, and 2.  
## Fix
This can easily be done in torch by setting the `X_train.targets` and `X_test.targets` manually. When the `idx` are found, the `np.where` statements are done consecutively, this results in `X_train.targets[idx]` being a tensor of 6s followed by 8s. This means `X_train.targets` can be replaced with a tensor of 0s followed by 1s. This can be quickly done using `torch.zeros` and `torch.ones` and then concatenated together in-place, no sweat. Replace line 61 with:
```
X_train.targets = torch.cat((torch.zeros((n_samples)), torch.ones((n_samples))))
```
and replace line 105 with:
```
X_test.targets = torch.cat((torch.zeros((n_samples)), torch.ones((n_samples))))
```
The code reuses `n_samples` so makes life even easier. Later the code uses the `DataLoader`class to shuffle everything up for you. With these changes, the code ran fine for me and if you need to add another class add another tensor using `torch.full((n_samples), class_number)` which will create a tensor of shape n_samples filled with the `class_number` specified. This will need to be concatenated with the other targets. For more info on creating torch tensors look [here](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) or check out the [documentation](https://pytorch.org/docs/stable/torch.html).

**Comment by phanducthien82** [comment]
Thanks a lot. It worked
