### ISSUE TITLE
Migrate `qiskit_algorithms` following end-of-support

### ISSUE THREAD

**Issue by edoaltamura** [qiskit-community/qiskit-machine-learning#811]
### What should we add?

Qiskit algorithms, which Qiskit machine-learning (ML) depends on, is no longer officially supported as of https://github.com/qiskit-community/qiskit-algorithms/commit/4247d063c807af01a3ebae9018e189cebb80a112. To continue improving the subset of Algorithms features that are relevant to Qiskit machine-learning, it has been proposed to migrate those from Algorithms to ML.

This proposed action would migrate three sections of Qiskit algorithms.

### Gradients https://github.com/qiskit-community/qiskit-algorithms/tree/main/qiskit_algorithms/gradients
* [x] The SPSA gradient submodule would be integrated directly into Qiskit ML. This includes **Estimator** and **Sampler** implementations. https://github.com/qiskit-community/qiskit-algorithms/tree/main/qiskit_algorithms/gradients/spsa
* [x] The Quantum Fischer Information submodules: https://github.com/qiskit-community/qiskit-algorithms/blob/main/qiskit_algorithms/gradients/qfi.py and https://github.com/qiskit-community/qiskit-algorithms/blob/main/qiskit_algorithms/gradients/qfi_result.py

### State fidelities https://github.com/qiskit-community/qiskit-algorithms/tree/main/qiskit_algorithms/state_fidelities
* [x] Base state fidelity
* [x] Compute-uncompute
* [x] State fidelity result

### Optimizers https://github.com/qiskit-community/qiskit-algorithms/tree/main/qiskit_algorithms/optimizers
The proposed migration could be applied in two stages.
* [x] First, the optimizers could be migrated alongside their respective wrapper classes.
* Second, the downstream usage could be tweaked so that the wrapper classes can be dropped and the optimizers imported directly from the original dependency. The feasibility of this step is to be evaluated after the standard migration.

## Utilities
* [x] The Algorithms migration would also affect utilities used by the above submodules, such as https://github.com/qiskit-community/qiskit-algorithms/blob/main/qiskit_algorithms/algorithm_job.py and https://github.com/qiskit-community/qiskit-algorithms/blob/main/qiskit_algorithms/algorithm_result.py.

---
The development will take place in this fork branch: https://github.com/OkuyanBoga/hc-qiskit-machine-learning/tree/migrate-algo.

**Comment by declanmillar** [comment]
I think this all sounds sensible. I suppose we'll also need to migrate the unit tests, and the tutorials may need to be modified to reflect the reduced functionality. Is the plan to migrate all the dependencies as-is before modifying them for compatibility with ISACircuits/V2 Primitives?

**Comment by edoaltamura** [comment]
This would be a valid solution. Migrating the relevant parts first would mean that we would only have to update the ISA/V2 compatibility on this subset of the code for the moment.
Thanks for pointing out the tests! We definitely need those too to maintain code coverage. I have merged the files and the tests will be in the `hc-` fork by tomorrow.
