### ISSUE TITLE
Run hybrid neural network on hardware or simulator with noise

### ISSUE THREAD

**Issue by Neon7799** [qiskit-community/qiskit-machine-learning#830]
Hi, is there any example to show how to run the hybrid QNNs in this [tutorial](https://github.com/qiskit-community/qiskit-machine-learning/blob/stable/0.7/docs/tutorials/05_torch_connector.ipynb) on hardware or simulator?

**Comment by woodsp-ibm** [comment]
By default SamplerQNN uses the Qiskit Sampler and EstimatorQNN the Qiskit Estimator. SamplerQNN has a sampler parameter in its constructor where you can specify a different one to be used, e.g. the Sampler from Qsikit Aer, EstimatorQNN has estimator parameter. So create an Aer primitive instance (not a V2 version though - see below) and pass that explicitly when you construct a QNN. You can set Qiskit Aer simulator to include noise and with the Aer primitive being used by the QNN that's where it will run.

On a real backend things no longer work there presently. Qiskit Machine Learning uses the original (Version 1) primitives and they have been superseded by V2 versions which are different. While Qiskit Aer still has the V1 versions (as does Qiskit) in the IBM Runtime, needed to run on real devices, V1 primitives were deprecated and already removed. There is an issue #742 to update code here for V2 primitive support but this work has yet to happen.
