### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by arthiudayak** [qiskit-community/qiskit-machine-learning#859]
### Environment

- qiskit_machine_learning-0.8.0
- Python 3.10.15
- Sagemaker - g5.xlarge - ubuntu 

### What is happening?

While install qiskit_machine_learning-0.8.0 , its working in Google Colab but in ASW Sagemaker its throwing an error in metadata generation. 

Collecting fastdtw (from qiskit_machine_learning)
  Downloading fastdtw-0.3.4.tar.gz (133 kB)
  Preparing metadata (setup.py) ... error

### How can we reproduce the issue?

Its an installation and compatibility  issue 

### What should happen?

It should downloaded correctly. 

### Any suggestions?
This fastdtw dependency is causing the issue, Its working without this package, and looking at the versions of fastdtw  its from 2019, there is no recent updates. Any alternate to package to be found for this  approximate Dynamic Time Warping (DTW). else remove this dependency.

**Comment by edoaltamura** [comment]
Effectively `fastdtw` only appears in the requirements: https://github.com/qiskit-community/qiskit-machine-learning/blob/d557bb3f18cdd48762488f767beff057ef339f34/requirements.txt#L6
and nowhere else in the codebase. Also `requirements-dev.txt` doesn't have it as a dependency, so it should be possible to safely remove it. @woodsp-ibm @adekusar-drl could you please confirm whether this is the case?
